# Generated by Django 5.2.8 on 2025-11-20 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "dni",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                (
                    "comunidad_indigena",
                    models.CharField(
                        choices=[
                            ("QOM", "Qom (Toba)"),
                            ("MOQOIT", "Moqoit (Mocoví)"),
                            ("WICHI", "Wichí (Mataco)"),
                            ("NINGUNA", "Ninguna / No Aplica"),
                        ],
                        default="NINGUNA",
                        max_length=11,
                    ),
                ),
                (
                    "discapacidad",
                    models.CharField(
                        choices=[
                            ("SI", "Sí, la persona tiene una discapacidad"),
                            ("NO", "No aplica"),
                        ],
                        default="NO",
                    ),
                ),
            ],
            options={
                "db_table": "alumnos",
            },
        ),
        migrations.CreateModel(
            name="Grado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cueanexo", models.IntegerField()),
                (
                    "nombre_grado",
                    models.CharField(
                        choices=[
                            ("PRIMERO", "1er Grado"),
                            ("SEGUNDO", "2do Grado"),
                            ("TERCERO", "3er Grado"),
                            ("CUARTO", "4to Grado"),
                            ("QUINTO", "5to Grado"),
                            ("SEXTO", "6to Grado"),
                            ("SEPTIMO", "7mo Grado"),
                        ],
                        default="SEGUNDO",
                        max_length=8,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        choices=[("MANANA", "Mañana"), ("TARDE", "Tarde")],
                        default="MANANA",
                        max_length=6,
                    ),
                ),
            ],
            options={
                "db_table": "grados",
            },
        ),
        migrations.CreateModel(
            name="EvaluacionFluidezLectora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_palabras_leidas", models.IntegerField(default=0, null=True)),
                (
                    "pregunta_1",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_2",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_3",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_4",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_5",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "pregunta_6",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("NORESPONDE", "NoResponde"),
                        ],
                        default="NORESPONDE",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "asistencia",
                    models.CharField(
                        choices=[("PRESENTE", "Presente"), ("AUSENTE", "Ausente")],
                        default="AUSENTE",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones_educativas.alumno",
                    ),
                ),
            ],
            options={
                "db_table": "evaluaciones_fluidez_lectora",
            },
        ),
        migrations.AddField(
            model_name="alumno",
            name="grado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluaciones_educativas.grado",
            ),
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seccion",
                    models.CharField(
                        choices=[
                            ("UNICO", "Unico"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                            ("K", "K"),
                        ],
                        default="UNICO",
                        max_length=5,
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones_educativas.grado",
                    ),
                ),
            ],
            options={
                "db_table": "secciones",
                "unique_together": {("seccion", "grado")},
            },
        ),
    ]
